### PR TITLE
Make attribute viewer configureable with FFF_STAT_CMD

### PR DESCRIPTION
**Pull request by FriendlyNeighborhoodShane**
Hello! Just a little more configuration. I couldn't quite figure out the current logic of configuration variables using := or :- so I went with the latter (used for opener command)

### CODE REVIEW

**Comment by FriendlyNeighborhoodShane** [comment]
Fuck wait nooooooo I messed up the second docpage

**Comment by FriendlyNeighborhoodShane** [comment]
Oh. Github is smarter than I thought. It automatically added the force-pushed commit to the PR.

**Comment by FriendlyNeighborhoodShane** [comment]
BTW @dylanaraps I plan to make another change, because the current selection mechanism (separate select/select all button for each action but only one execute button which executes the command used for the last select) is weird and documentationally unclear. Any specific reason why it is so?


I plan to change it to:
 - Action agnostic select button and select all button
 - Four action keys that act on the agnostic selection

**Comment by dylanaraps** [comment]
Send another pull request. I'm not sure yet if I like the proposed change to selections (though at the same time, I can't be 100% sure unless I actually try it). :+1:

**Pull request merged**
